# Generated by Django 2.0 on 2018-01-18 08:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('human', '0002_dailyperformer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.TextField()),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='human.Relationship')),
            ],
        ),
        migrations.RemoveField(
            model_name='dailyperformer',
            name='client',
        ),
        migrations.RemoveField(
            model_name='dailyperformer',
            name='performer',
        ),
        migrations.DeleteModel(
            name='DailyPerformer',
        ),
    ]
