# Generated by Django 2.0 on 2018-01-18 08:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('human', '0003_auto_20180118_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship',
            name='label',
            field=models.SlugField(default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
    ]
