# Generated by Django 2.0 on 2018-01-18 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('human', '0004_relationship_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='handle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
