# Generated by Django 2.0 on 2018-02-15 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human', '0009_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='job',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='nickname',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
