# Generated by Django 2.0 on 2018-01-23 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('earth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holdingvocher',
            name='used',
        ),
        migrations.AlterField(
            model_name='holdingvocher',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='holdingvocher',
            name='vocher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='earth.Vocher'),
        ),
        migrations.AlterField(
            model_name='vocher',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='earth.Store'),
        ),
    ]
