# Generated by Django 2.0 on 2018-01-23 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earth', '0002_auto_20180123_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='holdingvocher',
            name='label',
            field=models.SlugField(default='12313', unique=False),
            preserve_default=False,
        ),
    ]
