# Generated by Django 2.0 on 2018-01-23 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earth', '0003_holdingvocher_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holdingvocher',
            name='label',
            field=models.SlugField(unique=True),
        ),
    ]
